FROM node:12.16-alpine

RUN apk --no-cache add \
  bash \
  git \
  jq

RUN npm install -g sequelize-cli

WORKDIR /app

COPY ./package.json .

RUN npm install -s --no-optional && npm cache clean --force
COPY . .
RUN chmod +x /app/bin/run-app.sh

CMD ["npm", "run", "local:start"]