version: "3.2"

services:

  processor:
    build:
      dockerfile: Dockerfile.local
      context: ../services/service-processor
    # Disable logging for easier debugging
    # logging:
    #   driver: none
    environment:
      - VPC_NAME=development
      - AWS_REGION=us-west-2
      - PORT=9000
    volumes:
      - /app/node_modules
      - ../services/service-processor:/app
    depends_on:
      - processor-db
    ports:
      - '9000:9000'
    restart: always

  processor-db:
    image: 'postgres:latest'
    logging:
      driver: none
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '9001:5432'
    restart: always
